#ifndef DEVICE_CONFIG_H
#define DEVICE_CONFIG_H
/// BLE SERIAL EMULATOR
#define DEBUG

#define DEBUG_BLE_SERIAL_EMULATOR
//
#ifdef ENABLE_CAN_FEATURE
#define CAN_FEATURE
#endif

// #define COMMANDER_SERIAL_TO_BLE
//
/// SENSOR DATA LOG
#define DEBUG_DATA_LOG
#endif

//
#ifdef DEBUG
#define CONFIG_NIMBLE_CPP_LOG_LEVEL 4
#endif