name: CI
on:
  workflow_dispatch:
  push:
    branches: 
      - main
env:
  NODE_VERSION: '20.x'
  JAVA_VERSION: '22'

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: NPM Install
        run: npm install

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: adopt
          cache: gradle
          cache-dependency-path: android/build.gradle

      - name: Build APK
        working-directory: android
        run: ./gradlew assembleRelease
  
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: android/app/build/outputs/apk/release/app-release.apk

  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: NPM Install
        run: npm install

     
  
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ios/build/app-release.ipa
