name: CI
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ios, android]
        builderOs: [macos-latest, ubuntu-latest]
        include:
          - os: ios
            builderOs: macos-latest
          - os: android
            builderOs: ubuntu-latest
    runs-on: ${{ matrix.builderOs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
