name: CI
on:
  workflow_dispatch:
  push:
    branches: 
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ios, android]
        builderOs: [macos-latest, ubuntu-latest]
        exclude:
          - os: ios
            builderOs: ubuntu-latest
          - os: android
            builderOs: macos-latest
    runs-on: ${{ matrix.builderOs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: NPM Install
        run: npm install

      - name: Setup Java JDK
        if: matrix.os == 'android'
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 21
          distribution: microsoft
          cache: gradle
          cache-dependency-path: android/build.gradle

      # - name: Setup Android SDK Tools
      #   if: matrix.os == 'android'
      #   uses: android-actions/setup-android@v3.2.1

      - name: Install Android dependencies
        working-directory: android
        if: matrix.os == 'android'
        run: ./gradlew --no-daemon installRelease
  
