name: CI
on:
  workflow_dispatch:
  push:
    branches: 
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ios, android]
        builderOs: [macos-latest, ubuntu-latest]
        exclude:
          - os: ios
            builderOs: ubuntu-latest
          - os: android
            builderOs: macos-latest
    runs-on: ${{ matrix.builderOs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json
